# kubectl apply -f medalid-chaparro-03-secret.yml
# kubectl delete -f medalid-chaparro-03-secret.yml

apiVersion: v1

kind: Secret

metadata:
  name: medalid-chaparro-03-secret
  namespace: medalid-chaparro-03-namespace

type: Opaque

data:
  MONGODB_URI: bW9uZ29kYitzcnY6Ly9tZWRhbGlkY2hhcGFycm9fZGJfdXNlcjpDWUlhZHNINDNDU1NWMDhmQGNsdXN0ZXIwLmcyZHpjdm4ubW9uZ29kYi5uZXQvYWdyb3RlY25vX2RiP2FwcE5hbWU9Q2x1c3RlcjA=